/*
ITS kernel virtual key code conversion tables (QWERTY).
See https://wiki.osdev.org/PS/2_Keyboard#Scan_Code_Set_1
*/

#include <io/keycodes.h>

vkey_t oneByteScanCodeConversionTable[] = 
{
	// 0x00
	VKEY_INVALID, VKEY_ESC, VKEY_1, VKEY_2,
	VKEY_3, VKEY_4, VKEY_5, VKEY_6, 
	VKEY_7, VKEY_8, VKEY_9, VKEY_0,
	VKEY_MINUS, VKEY_EQUAL, VKEY_BACKSPACE, VKEY_TAB, 

	// 0x10
	VKEY_Q, VKEY_W, VKEY_E, VKEY_R,
	VKEY_T, VKEY_Y, VKEY_U, VKEY_I, 
	VKEY_O, VKEY_P, VKEY_LBRACKET, VKEY_RBRACKET,
	VKEY_ENTER, VKEY_LCONTROL, VKEY_A, VKEY_S, 

	// 0x20
	VKEY_D, VKEY_F, VKEY_G, VKEY_H, VKEY_J,
	VKEY_K, VKEY_L, VKEY_SEMICOLON, 
	VKEY_SQUOTE, VKEY_BACKTICK, VKEY_LSHIFT, VKEY_BACKSLASH,
	VKEY_Z, VKEY_X, VKEY_C, VKEY_V, 

	// 0x30
	VKEY_B, VKEY_N, VKEY_M, VKEY_COMMA, VKEY_DOT,
	VKEY_SLASH, VKEY_RSHIFT, VKEY_KPMULTIPLY, 
	VKEY_LALT, VKEY_SPACE, VKEY_CAPSLOCK, VKEY_F1,
	VKEY_F2, VKEY_F3, VKEY_F4, VKEY_F5, 

	// 0x40
	VKEY_F6, VKEY_F7, VKEY_F8, VKEY_F9,
	VKEY_F10, VKEY_NUMLOCK, VKEY_SCRLOCK, VKEY_KP7, 
	VKEY_KP8, VKEY_KP9, VKEY_KPMINUS, VKEY_KP4,
	VKEY_KP5, VKEY_KP6, VKEY_KPPLUS, VKEY_KP1, 

	// 0x50
	VKEY_KP2, VKEY_KP3, VKEY_KP0, VKEY_KPDOT,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_F11, 
	VKEY_F12, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,

	// 0x60
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,

	// 0x70
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
};

vkey_t e0ScanCodeConversionTable[] = 
{
	// 0x00
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	
	// 0x10
	VKEY_MMPREVTRACK, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_MMNEXTTRACK, VKEY_INVALID, VKEY_INVALID,
	VKEY_KPENTER, VKEY_RCONTROL, VKEY_INVALID, VKEY_INVALID,
	
	// 0x20
	VKEY_MMMUTE, VKEY_MMCALC, VKEY_MMPLAY, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_MMVOLDOWN, VKEY_INVALID,
	
	// 0x30
	VKEY_MMVOLUP, VKEY_INVALID, VKEY_MMWWW, VKEY_INVALID,
	VKEY_INVALID, VKEY_KPDIV, VKEY_INVALID, VKEY_INVALID, 
	VKEY_RALT, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	
	// 0x40
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_HOME, 
	VKEY_CURSORUP, VKEY_PAGEUP, VKEY_INVALID, VKEY_CURSORLEFT,
	VKEY_INVALID, VKEY_CURSORRIGHT, VKEY_INVALID, VKEY_END,
	
	// 0x50
	VKEY_CURSORDOWN, VKEY_PAGEDOWN, VKEY_INSERT, VKEY_DELETE,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_LGUI,
	VKEY_RGUI, VKEY_APPS, VKEY_ACPIPOWER, VKEY_ACPISLEEP,
	
	// 0x60
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_ACPIWAKE,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	
	// 0x70
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, 
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
	VKEY_INVALID, VKEY_INVALID, VKEY_INVALID, VKEY_INVALID,
};